post http://localhost:3001/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphNzAiLCJpZCI6IjVlN2Y2NjBjY2RlNjY5NGRlNTE1Yjc3NiIsImlhdCI6MTU4NTQxMjA5N30.9BmwsVoU_vmcbl2RuqlXouCWR0t_u7lfen-3bcxht3c

{
    "title": " JA TAAS tokenilla",
    "author": "jaa-a",
    "url": "fi",
    "likes": 2
    }